### ISSUE TITLE
prevent frustrating death situations

### ISSUE THREAD

**Issue by pocinhas** [o7q/KineticDamage#2]
**Is your feature request related to a problem? Please describe.**
its kind of annoying when i trying to walk backwards and i end up just pulling the mob im trying to get away from, to me

**Describe the solution you'd like**
maybe add a config option to make the entity take vanilla's knockback when the player is walking backwards?

**Describe alternatives you've considered**
when walking backwards, just dont deal knockback at all, though i think i would prefer my other solution

**Additional context**
i get this is literally the whole point of the mod, but this would actually make the mod good for general play!

**Comment by o7q** [comment]
Thanks for the feedback, when I get to time to update it I will consider your issues. Should be a pretty easy fix.
