### ISSUE TITLE
entity specific config

### ISSUE THREAD

**Issue by pocinhas** [o7q/KineticDamage#3]
**Is your feature request related to a problem? Please describe.**
i noticed i could make polar bears go flying, but not players

**Describe the solution you'd like**
instead of suggesting an entity specific solution, i think maybe a more general approach - being able to config damage and knockback per entity id - would be better (also good for mod support or modpack usage). i specifically want to use this myself to make players take more knockback, but it would definitely make your amazing mod have a more viable usage for modpacks with custom entities

**Describe alternatives you've considered**
none really. maybe [Pehkui](https://modrinth.com/mod/pehkui)'s size compatibility, if there isn't already?

**Additional context**
very cool mod btw dude :D

**Comment by o7q** [comment]
Players should be able to take knockback, it might be buggier when running server-side.
