### ISSUE TITLE
toggle vanilla kb + mod's kb

### ISSUE THREAD

**Issue by pocinhas** [o7q/KineticDamage#4]
**Is your feature request related to a problem? Please describe.**
its kind of scary engaging in fights with any mob considering the first few hits can be risky since you deal little to no knockback at the start

**Describe the solution you'd like**
add an option in the config to make the mod use the vanilla kb (or let us configure the knockback) added to the knockback from the vectorial calculations from KineticDamage

**Describe alternatives you've considered**
i dont like this alternative so much, but alternatively, let the user control the ground drag that affects the hit entity's movement

**Comment by o7q** [comment]
If I come back to working on this mod, I'll definitely add this feature. Thank you!
