### ISSUE TITLE
Clicking on a player while in spectator mode damages them.

### ISSUE THREAD

**Issue by NoThrottle** [o7q/KineticDamage#7]
**Describe the bug**
When you go to spectate a player and lock on to their POV, you have to left click (attack) them, this induced damage AND knockback on to the player.

**To Reproduce**
1. Find a player you want to be confused.
2. Change into Spectator mode
3. Approach them with speed while spamming your mouse on them.
4. Success, they're confused and hurt.

**Expected behavior**
You just lock on to their POV, no damage occurs.

**Additional context**
Works on mobs too, and generally any entity with HP.

**Comment by o7q** [comment]
Ah, this actually makes a lot of sense, it has to do with how the player hit detection works. It does not check to see if the player is in spectator mode. Unfortunately I have very little time to work on this mod so I will need to put this off for a good while.
