### ISSUE TITLE
The mod needs more damage feed back

### ISSUE THREAD

**Issue by ILLUMN8N** [o7q/KineticDamage#8]
**Is your feature request related to a problem? Please describe.**
I love the mod, but when you hit the fastest slice of all time, there's no real feed back, like the critical hit has the crunch sound, and the kb hit has it's whack sound

**Describe the solution you'd like**
Use kb hit sounds for upper cuts and critical hit sounds for very fast hits

**Comment by o7q** [comment]
That's a great idea and I was thinking the same thing myself, unfortunately I am quite thin on time these days to work on the mod, and I am going to put this on hold for a good while. Thanks for the feedback though, I really appreciate it!
